artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_data_file: streamlit_files/data.csv
  source_info_file: streamlit_files/additional_data.json
  local_data_name: data.csv

data_visualization:
  root_dir: artifacts/data_visualization
  data_file_path: artifacts/data_ingestion/data.csv
  info_file_path: artifacts/data_ingestion/data_info.json

prompt_generation:
  root_dir: artifacts/prompt_generation
  data_path: artifacts/data_ingestion/data.csv
  visualization_path: artifacts/data_visualization/
  data_information_file: artifacts/data_ingestion/data_info.json
  prompt_file_name: prompt.txt
  images_file_name: images.joblib

prompting:
  root_dir: artifacts/prompting
  model_name: gemini-pro-vision
  response_file_name: response.json
  candidates_file_name: candidates.json
  project_name: ultra-heading-407815
  project_location: us-central1
  prompt_file_path: artifacts/prompt_generation/prompt.txt
  images_file_path: artifacts/prompt_generation/images.joblib
  trulens_db_name: gemInsights.sqlite